# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20170821_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='RMSE',
            field=models.IntegerField(max_length=20),
        ),
    ]
