# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(964, 626)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/MainWindowIcon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.dataintegrationTab = QtGui.QWidget()
        self.dataintegrationTab.setObjectName(_fromUtf8("dataintegrationTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dataintegrationTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.dataintegrationTab)
        self.label_8.setMinimumSize(QtCore.QSize(120, 0))
        self.label_8.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.dbConnectionActiveLabel = QtGui.QLabel(self.dataintegrationTab)
        self.dbConnectionActiveLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.dbConnectionActiveLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.dbConnectionActiveLabel.setPalette(palette)
        self.dbConnectionActiveLabel.setAutoFillBackground(True)
        self.dbConnectionActiveLabel.setText(_fromUtf8(""))
        self.dbConnectionActiveLabel.setObjectName(_fromUtf8("dbConnectionActiveLabel"))
        self.gridLayout.addWidget(self.dbConnectionActiveLabel, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.dataintegrationTab)
        self.label_7.setMinimumSize(QtCore.QSize(120, 0))
        self.label_7.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.startRestPushButton = QtGui.QPushButton(self.dataintegrationTab)
        self.startRestPushButton.setMinimumSize(QtCore.QSize(160, 0))
        self.startRestPushButton.setMaximumSize(QtCore.QSize(160, 16777215))
        self.startRestPushButton.setObjectName(_fromUtf8("startRestPushButton"))
        self.gridLayout.addWidget(self.startRestPushButton, 1, 1, 1, 1)
        self.restServerActiveLabel = QtGui.QLabel(self.dataintegrationTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restServerActiveLabel.sizePolicy().hasHeightForWidth())
        self.restServerActiveLabel.setSizePolicy(sizePolicy)
        self.restServerActiveLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.restServerActiveLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.restServerActiveLabel.setPalette(palette)
        self.restServerActiveLabel.setAutoFillBackground(True)
        self.restServerActiveLabel.setText(_fromUtf8(""))
        self.restServerActiveLabel.setObjectName(_fromUtf8("restServerActiveLabel"))
        self.gridLayout.addWidget(self.restServerActiveLabel, 1, 2, 1, 1)
        self.connectToDatabasePushButton = QtGui.QPushButton(self.dataintegrationTab)
        self.connectToDatabasePushButton.setMinimumSize(QtCore.QSize(160, 0))
        self.connectToDatabasePushButton.setMaximumSize(QtCore.QSize(160, 16777215))
        self.connectToDatabasePushButton.setObjectName(_fromUtf8("connectToDatabasePushButton"))
        self.gridLayout.addWidget(self.connectToDatabasePushButton, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.currentDatabaseConnectionLabel = QtGui.QLabel(self.dataintegrationTab)
        self.currentDatabaseConnectionLabel.setText(_fromUtf8(""))
        self.currentDatabaseConnectionLabel.setObjectName(_fromUtf8("currentDatabaseConnectionLabel"))
        self.verticalLayout_2.addWidget(self.currentDatabaseConnectionLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.databaseTableWidget = QtGui.QTableWidget(self.dataintegrationTab)
        self.databaseTableWidget.setObjectName(_fromUtf8("databaseTableWidget"))
        self.databaseTableWidget.setColumnCount(0)
        self.databaseTableWidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.databaseTableWidget)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.addEntryButton = QtGui.QPushButton(self.dataintegrationTab)
        self.addEntryButton.setMinimumSize(QtCore.QSize(160, 0))
        self.addEntryButton.setMaximumSize(QtCore.QSize(160, 16777215))
        self.addEntryButton.setObjectName(_fromUtf8("addEntryButton"))
        self.verticalLayout.addWidget(self.addEntryButton)
        self.deleteEntryButton = QtGui.QPushButton(self.dataintegrationTab)
        self.deleteEntryButton.setMinimumSize(QtCore.QSize(160, 0))
        self.deleteEntryButton.setMaximumSize(QtCore.QSize(160, 16777215))
        self.deleteEntryButton.setObjectName(_fromUtf8("deleteEntryButton"))
        self.verticalLayout.addWidget(self.deleteEntryButton)
        self.editButton = QtGui.QPushButton(self.dataintegrationTab)
        self.editButton.setMinimumSize(QtCore.QSize(160, 0))
        self.editButton.setMaximumSize(QtCore.QSize(160, 16777215))
        self.editButton.setObjectName(_fromUtf8("editButton"))
        self.verticalLayout.addWidget(self.editButton)
        self.deleteTableButton = QtGui.QPushButton(self.dataintegrationTab)
        self.deleteTableButton.setMinimumSize(QtCore.QSize(160, 0))
        self.deleteTableButton.setMaximumSize(QtCore.QSize(160, 16777215))
        self.deleteTableButton.setObjectName(_fromUtf8("deleteTableButton"))
        self.verticalLayout.addWidget(self.deleteTableButton)
        self.refreshTableButton = QtGui.QPushButton(self.dataintegrationTab)
        self.refreshTableButton.setMinimumSize(QtCore.QSize(160, 0))
        self.refreshTableButton.setObjectName(_fromUtf8("refreshTableButton"))
        self.verticalLayout.addWidget(self.refreshTableButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_5 = QtGui.QLabel(self.dataintegrationTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.textEdit = QtGui.QTextEdit(self.dataintegrationTab)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_2.addWidget(self.textEdit)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.dataintegrationTab, _fromUtf8(""))
        self.analyseTab = QtGui.QWidget()
        self.analyseTab.setObjectName(_fromUtf8("analyseTab"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.analyseTab)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_18 = QtGui.QLabel(self.analyseTab)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_6.addWidget(self.label_18)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_16 = QtGui.QLabel(self.analyseTab)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_6.addWidget(self.label_16)
        self.chooseAlgoComboBox = QtGui.QComboBox(self.analyseTab)
        self.chooseAlgoComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.chooseAlgoComboBox.setObjectName(_fromUtf8("chooseAlgoComboBox"))
        self.chooseAlgoComboBox.addItem(_fromUtf8(""))
        self.chooseAlgoComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.chooseAlgoComboBox)
        self.algoConfigButton = QtGui.QPushButton(self.analyseTab)
        self.algoConfigButton.setMinimumSize(QtCore.QSize(140, 0))
        self.algoConfigButton.setMaximumSize(QtCore.QSize(140, 16777215))
        self.algoConfigButton.setObjectName(_fromUtf8("algoConfigButton"))
        self.horizontalLayout_6.addWidget(self.algoConfigButton)
        self.applyAlgoButton = QtGui.QPushButton(self.analyseTab)
        self.applyAlgoButton.setMinimumSize(QtCore.QSize(140, 0))
        self.applyAlgoButton.setMaximumSize(QtCore.QSize(140, 16777215))
        self.applyAlgoButton.setObjectName(_fromUtf8("applyAlgoButton"))
        self.horizontalLayout_6.addWidget(self.applyAlgoButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.label_19 = QtGui.QLabel(self.analyseTab)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_6.addWidget(self.label_19)
        self.pipelinesTableWidget = QtGui.QTableWidget(self.analyseTab)
        self.pipelinesTableWidget.setObjectName(_fromUtf8("pipelinesTableWidget"))
        self.pipelinesTableWidget.setColumnCount(0)
        self.pipelinesTableWidget.setRowCount(0)
        self.verticalLayout_6.addWidget(self.pipelinesTableWidget)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.deletePipelineButton = QtGui.QPushButton(self.analyseTab)
        self.deletePipelineButton.setMinimumSize(QtCore.QSize(140, 0))
        self.deletePipelineButton.setMaximumSize(QtCore.QSize(140, 16777215))
        self.deletePipelineButton.setObjectName(_fromUtf8("deletePipelineButton"))
        self.horizontalLayout_5.addWidget(self.deletePipelineButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.line_3 = QtGui.QFrame(self.analyseTab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_6.addWidget(self.line_3)
        self.label_29 = QtGui.QLabel(self.analyseTab)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_6.addWidget(self.label_29)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.appliedFilterTableWidget = QtGui.QTableWidget(self.analyseTab)
        self.appliedFilterTableWidget.setObjectName(_fromUtf8("appliedFilterTableWidget"))
        self.appliedFilterTableWidget.setColumnCount(0)
        self.appliedFilterTableWidget.setRowCount(0)
        self.horizontalLayout_4.addWidget(self.appliedFilterTableWidget)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.chooseFilterComboBox = QtGui.QComboBox(self.analyseTab)
        self.chooseFilterComboBox.setMinimumSize(QtCore.QSize(140, 0))
        self.chooseFilterComboBox.setMaximumSize(QtCore.QSize(140, 16777215))
        self.chooseFilterComboBox.setObjectName(_fromUtf8("chooseFilterComboBox"))
        self.chooseFilterComboBox.addItem(_fromUtf8(""))
        self.chooseFilterComboBox.addItem(_fromUtf8(""))
        self.chooseFilterComboBox.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.chooseFilterComboBox)
        self.configureFilterButton = QtGui.QPushButton(self.analyseTab)
        self.configureFilterButton.setMinimumSize(QtCore.QSize(140, 0))
        self.configureFilterButton.setMaximumSize(QtCore.QSize(140, 16777215))
        self.configureFilterButton.setObjectName(_fromUtf8("configureFilterButton"))
        self.verticalLayout_4.addWidget(self.configureFilterButton)
        self.deleteFilterButton = QtGui.QPushButton(self.analyseTab)
        self.deleteFilterButton.setMinimumSize(QtCore.QSize(140, 0))
        self.deleteFilterButton.setMaximumSize(QtCore.QSize(140, 16777215))
        self.deleteFilterButton.setObjectName(_fromUtf8("deleteFilterButton"))
        self.verticalLayout_4.addWidget(self.deleteFilterButton)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(137, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.addFilterButton = QtGui.QPushButton(self.analyseTab)
        self.addFilterButton.setMinimumSize(QtCore.QSize(140, 0))
        self.addFilterButton.setMaximumSize(QtCore.QSize(140, 16777215))
        self.addFilterButton.setObjectName(_fromUtf8("addFilterButton"))
        self.verticalLayout_4.addWidget(self.addFilterButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.line = QtGui.QFrame(self.analyseTab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_7.addWidget(self.line)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_17 = QtGui.QLabel(self.analyseTab)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_7.addWidget(self.label_17)
        self.pipelineInfoTextEdit = QtGui.QPlainTextEdit(self.analyseTab)
        self.pipelineInfoTextEdit.setReadOnly(True)
        self.pipelineInfoTextEdit.setObjectName(_fromUtf8("pipelineInfoTextEdit"))
        self.verticalLayout_7.addWidget(self.pipelineInfoTextEdit)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.startStopAnalysisPushButton = QtGui.QPushButton(self.analyseTab)
        self.startStopAnalysisPushButton.setMinimumSize(QtCore.QSize(140, 0))
        self.startStopAnalysisPushButton.setMaximumSize(QtCore.QSize(140, 16777215))
        self.startStopAnalysisPushButton.setObjectName(_fromUtf8("startStopAnalysisPushButton"))
        self.horizontalLayout_3.addWidget(self.startStopAnalysisPushButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.tabWidget.addTab(self.analyseTab, _fromUtf8(""))
        self.resultsTab = QtGui.QWidget()
        self.resultsTab.setObjectName(_fromUtf8("resultsTab"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.resultsTab)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.resultsTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.predictionAccuracyLineEdit = QtGui.QLineEdit(self.resultsTab)
        self.predictionAccuracyLineEdit.setReadOnly(True)
        self.predictionAccuracyLineEdit.setObjectName(_fromUtf8("predictionAccuracyLineEdit"))
        self.gridLayout_2.addWidget(self.predictionAccuracyLineEdit, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.resultsTab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.junkPercentageLineEdit = QtGui.QLineEdit(self.resultsTab)
        self.junkPercentageLineEdit.setReadOnly(True)
        self.junkPercentageLineEdit.setObjectName(_fromUtf8("junkPercentageLineEdit"))
        self.gridLayout_2.addWidget(self.junkPercentageLineEdit, 1, 1, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.label = QtGui.QLabel(self.resultsTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_8.addWidget(self.label)
        self.reportTextEdit = QtGui.QPlainTextEdit(self.resultsTab)
        self.reportTextEdit.setObjectName(_fromUtf8("reportTextEdit"))
        self.verticalLayout_8.addWidget(self.reportTextEdit)
        self.horizontalLayout_9.addLayout(self.verticalLayout_8)
        self.line_2 = QtGui.QFrame(self.resultsTab)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_9.addWidget(self.line_2)
        self.plotLabel1 = QtGui.QLabel(self.resultsTab)
        self.plotLabel1.setMinimumSize(QtCore.QSize(700, 300))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.plotLabel1.setPalette(palette)
        self.plotLabel1.setAutoFillBackground(True)
        self.plotLabel1.setText(_fromUtf8(""))
        self.plotLabel1.setObjectName(_fromUtf8("plotLabel1"))
        self.horizontalLayout_9.addWidget(self.plotLabel1)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.resultsTab, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuBearbeiten = QtGui.QMenu(self.menubar)
        self.menuBearbeiten.setObjectName(_fromUtf8("menuBearbeiten"))
        self.menuHilfe = QtGui.QMenu(self.menubar)
        self.menuHilfe.setObjectName(_fromUtf8("menuHilfe"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNewFile = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/New.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionNewFile.setIcon(icon1)
        self.actionNewFile.setObjectName(_fromUtf8("actionNewFile"))
        self.actionOpenNewDatabase = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/OpenNewDatabase.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenNewDatabase.setIcon(icon2)
        self.actionOpenNewDatabase.setObjectName(_fromUtf8("actionOpenNewDatabase"))
        self.actionSaveFile = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveFile.setIcon(icon3)
        self.actionSaveFile.setObjectName(_fromUtf8("actionSaveFile"))
        self.actionQuit = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Quit.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionQuit.setIcon(icon4)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionPrint = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Print.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPrint.setIcon(icon5)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionOnlineAnalysis = QtGui.QAction(MainWindow)
        self.actionOnlineAnalysis.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/OnlineAnalysis.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOnlineAnalysis.setIcon(icon6)
        self.actionOnlineAnalysis.setObjectName(_fromUtf8("actionOnlineAnalysis"))
        self.actionActionOpenProject = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/FileOpen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionActionOpenProject.setIcon(icon7)
        self.actionActionOpenProject.setObjectName(_fromUtf8("actionActionOpenProject"))
        self.actionHelpAbout = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/Help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelpAbout.setIcon(icon8)
        self.actionHelpAbout.setObjectName(_fromUtf8("actionHelpAbout"))
        self.actionSaveFileAs = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/SaveAs.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSaveFileAs.setIcon(icon9)
        self.actionSaveFileAs.setObjectName(_fromUtf8("actionSaveFileAs"))
        self.menuFile.addAction(self.actionSaveFile)
        self.menuFile.addAction(self.actionSaveFileAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuBearbeiten.addAction(self.actionOpenNewDatabase)
        self.menuBearbeiten.addAction(self.actionOnlineAnalysis)
        self.menuHilfe.addAction(self.actionHelpAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBearbeiten.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())
        self.toolBar.addAction(self.actionSaveFile)
        self.toolBar.addAction(self.actionSaveFileAs)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOpenNewDatabase)
        self.toolBar.addAction(self.actionOnlineAnalysis)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHelpAbout)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addSeparator()
        self.label_16.setBuddy(self.chooseAlgoComboBox)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Prototyp - Automatisierte industrielle Datenanalyse", None))
        self.label_8.setText(_translate("MainWindow", "Datenbank", None))
        self.label_7.setText(_translate("MainWindow", "REST Server", None))
        self.startRestPushButton.setText(_translate("MainWindow", "Starten", None))
        self.connectToDatabasePushButton.setText(_translate("MainWindow", "Verbinden", None))
        self.addEntryButton.setText(_translate("MainWindow", "&Hinzufügen", None))
        self.deleteEntryButton.setText(_translate("MainWindow", "&Löschen", None))
        self.editButton.setText(_translate("MainWindow", "&Editieren", None))
        self.deleteTableButton.setText(_translate("MainWindow", "Tabelle Löschen", None))
        self.refreshTableButton.setText(_translate("MainWindow", "&Aktualisieren", None))
        self.label_5.setText(_translate("MainWindow", "Datenbank Verbindung", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataintegrationTab), _translate("MainWindow", "Datenintegration", None))
        self.label_18.setText(_translate("MainWindow", "Neue Pipeline", None))
        self.label_16.setText(_translate("MainWindow", "&Algorithmus", None))
        self.chooseAlgoComboBox.setItemText(0, _translate("MainWindow", "KNeighborsClassifier", None))
        self.chooseAlgoComboBox.setItemText(1, _translate("MainWindow", "SimpleKMeans", None))
        self.algoConfigButton.setText(_translate("MainWindow", "Konfiguration", None))
        self.applyAlgoButton.setText(_translate("MainWindow", "Hinzufügen", None))
        self.label_19.setText(_translate("MainWindow", "Pipelines", None))
        self.deletePipelineButton.setText(_translate("MainWindow", "Entfernen", None))
        self.label_29.setText(_translate("MainWindow", " Filter", None))
        self.chooseFilterComboBox.setItemText(0, _translate("MainWindow", "None", None))
        self.chooseFilterComboBox.setItemText(1, _translate("MainWindow", "MinMaxFilter", None))
        self.chooseFilterComboBox.setItemText(2, _translate("MainWindow", "MeanFilter", None))
        self.configureFilterButton.setText(_translate("MainWindow", "Konfiguration", None))
        self.deleteFilterButton.setText(_translate("MainWindow", "Entfernen", None))
        self.addFilterButton.setText(_translate("MainWindow", "Hinzufügen", None))
        self.label_17.setText(_translate("MainWindow", "Parameter", None))
        self.startStopAnalysisPushButton.setText(_translate("MainWindow", "Starte Analyse", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analyseTab), _translate("MainWindow", "Analyse", None))
        self.label_4.setText(_translate("MainWindow", "Genauigkeit [%]", None))
        self.label_6.setText(_translate("MainWindow", "Ausschuss [%]", None))
        self.label.setText(_translate("MainWindow", "Bericht", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.resultsTab), _translate("MainWindow", "Auswertung", None))
        self.menuFile.setTitle(_translate("MainWindow", "Datei", None))
        self.menuBearbeiten.setTitle(_translate("MainWindow", "Bearbeiten", None))
        self.menuHilfe.setTitle(_translate("MainWindow", "Hilfe", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionNewFile.setText(_translate("MainWindow", "Neu...", None))
        self.actionNewFile.setIconText(_translate("MainWindow", "Neu...", None))
        self.actionNewFile.setToolTip(_translate("MainWindow", "Datei Öffnen", None))
        self.actionNewFile.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionOpenNewDatabase.setText(_translate("MainWindow", "Neue Datenbank Verbindung", None))
        self.actionOpenNewDatabase.setToolTip(_translate("MainWindow", "Neue Datenbank Verbindung herstellen", None))
        self.actionOpenNewDatabase.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionSaveFile.setText(_translate("MainWindow", "Speichern", None))
        self.actionSaveFile.setToolTip(_translate("MainWindow", "Analyseergebnisse speichern", None))
        self.actionSaveFile.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setToolTip(_translate("MainWindow", "Programm Beenden", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionPrint.setText(_translate("MainWindow", "Drucken", None))
        self.actionPrint.setToolTip(_translate("MainWindow", "Analyseergebnisse Drucken", None))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.actionOnlineAnalysis.setText(_translate("MainWindow", "Aktiviere Online Analyse", None))
        self.actionOnlineAnalysis.setToolTip(_translate("MainWindow", "Online Analyse Aktivieren/Deaktivieren", None))
        self.actionOnlineAnalysis.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionActionOpenProject.setText(_translate("MainWindow", "Öffnen...", None))
        self.actionActionOpenProject.setIconText(_translate("MainWindow", "Öffnen...", None))
        self.actionActionOpenProject.setToolTip(_translate("MainWindow", "Projekt Öffnen", None))
        self.actionHelpAbout.setText(_translate("MainWindow", "Über", None))
        self.actionHelpAbout.setToolTip(_translate("MainWindow", "Informationen Anzeigen", None))
        self.actionHelpAbout.setShortcut(_translate("MainWindow", "Ctrl+H", None))
        self.actionSaveFileAs.setText(_translate("MainWindow", "Speichern Unter", None))
        self.actionSaveFileAs.setToolTip(_translate("MainWindow", "Analyseergebnisse Speichern Unter", None))

import resources_rc
