# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1185, 785)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/MainWindowIcon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.dataintegrationTab = QtGui.QWidget()
        self.dataintegrationTab.setObjectName(_fromUtf8("dataintegrationTab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.dataintegrationTab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.dbLayout = QtGui.QVBoxLayout()
        self.dbLayout.setObjectName(_fromUtf8("dbLayout"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.connectToDatabasePushButton = QtGui.QPushButton(self.dataintegrationTab)
        self.connectToDatabasePushButton.setObjectName(_fromUtf8("connectToDatabasePushButton"))
        self.horizontalLayout_8.addWidget(self.connectToDatabasePushButton)
        self.dbLayout.addLayout(self.horizontalLayout_8)
        self.startLoggingSimulationPushButton = QtGui.QPushButton(self.dataintegrationTab)
        self.startLoggingSimulationPushButton.setObjectName(_fromUtf8("startLoggingSimulationPushButton"))
        self.dbLayout.addWidget(self.startLoggingSimulationPushButton)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_21 = QtGui.QLabel(self.dataintegrationTab)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_9.addWidget(self.label_21)
        self.workpieceSelectionComboBox = QtGui.QComboBox(self.dataintegrationTab)
        self.workpieceSelectionComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.workpieceSelectionComboBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.workpieceSelectionComboBox.setObjectName(_fromUtf8("workpieceSelectionComboBox"))
        self.horizontalLayout_9.addWidget(self.workpieceSelectionComboBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.dbLayout.addLayout(self.horizontalLayout_9)
        self.databaseContentHLayout = QtGui.QHBoxLayout()
        self.databaseContentHLayout.setObjectName(_fromUtf8("databaseContentHLayout"))
        self.tableVLayout = QtGui.QVBoxLayout()
        self.tableVLayout.setObjectName(_fromUtf8("tableVLayout"))
        self.currentDatabaseConnectionLabel = QtGui.QLabel(self.dataintegrationTab)
        self.currentDatabaseConnectionLabel.setObjectName(_fromUtf8("currentDatabaseConnectionLabel"))
        self.tableVLayout.addWidget(self.currentDatabaseConnectionLabel)
        self.databaseTableView = QtGui.QTableView(self.dataintegrationTab)
        self.databaseTableView.setObjectName(_fromUtf8("databaseTableView"))
        self.tableVLayout.addWidget(self.databaseTableView)
        self.databaseContentHLayout.addLayout(self.tableVLayout)
        self.buttonsVLayout = QtGui.QVBoxLayout()
        self.buttonsVLayout.setObjectName(_fromUtf8("buttonsVLayout"))
        self.addEntryButton = QtGui.QPushButton(self.dataintegrationTab)
        self.addEntryButton.setObjectName(_fromUtf8("addEntryButton"))
        self.buttonsVLayout.addWidget(self.addEntryButton)
        self.deleteEntryButton = QtGui.QPushButton(self.dataintegrationTab)
        self.deleteEntryButton.setObjectName(_fromUtf8("deleteEntryButton"))
        self.buttonsVLayout.addWidget(self.deleteEntryButton)
        self.editButton = QtGui.QPushButton(self.dataintegrationTab)
        self.editButton.setObjectName(_fromUtf8("editButton"))
        self.buttonsVLayout.addWidget(self.editButton)
        self.editCategoriesButton = QtGui.QPushButton(self.dataintegrationTab)
        self.editCategoriesButton.setObjectName(_fromUtf8("editCategoriesButton"))
        self.buttonsVLayout.addWidget(self.editCategoriesButton)
        self.deleteTableButton = QtGui.QPushButton(self.dataintegrationTab)
        self.deleteTableButton.setObjectName(_fromUtf8("deleteTableButton"))
        self.buttonsVLayout.addWidget(self.deleteTableButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.buttonsVLayout.addItem(spacerItem1)
        self.quitButton = QtGui.QPushButton(self.dataintegrationTab)
        self.quitButton.setObjectName(_fromUtf8("quitButton"))
        self.buttonsVLayout.addWidget(self.quitButton)
        self.databaseContentHLayout.addLayout(self.buttonsVLayout)
        self.dbLayout.addLayout(self.databaseContentHLayout)
        self.dbConnectionVLayout = QtGui.QVBoxLayout()
        self.dbConnectionVLayout.setObjectName(_fromUtf8("dbConnectionVLayout"))
        self.label_5 = QtGui.QLabel(self.dataintegrationTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.dbConnectionVLayout.addWidget(self.label_5)
        self.textEdit = QtGui.QTextEdit(self.dataintegrationTab)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.dbConnectionVLayout.addWidget(self.textEdit)
        self.dbLayout.addLayout(self.dbConnectionVLayout)
        self.horizontalLayout_3.addLayout(self.dbLayout)
        self.tabWidget.addTab(self.dataintegrationTab, _fromUtf8(""))
        self.analyseTab = QtGui.QWidget()
        self.analyseTab.setObjectName(_fromUtf8("analyseTab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.analyseTab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_18 = QtGui.QLabel(self.analyseTab)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_3.addWidget(self.label_18)
        self.line_5 = QtGui.QFrame(self.analyseTab)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_3.addWidget(self.line_5)
        self.chooseAlgorithmsHLayout = QtGui.QHBoxLayout()
        self.chooseAlgorithmsHLayout.setObjectName(_fromUtf8("chooseAlgorithmsHLayout"))
        self.label_16 = QtGui.QLabel(self.analyseTab)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.chooseAlgorithmsHLayout.addWidget(self.label_16)
        self.chooseAlgoComboBox = QtGui.QComboBox(self.analyseTab)
        self.chooseAlgoComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.chooseAlgoComboBox.setObjectName(_fromUtf8("chooseAlgoComboBox"))
        self.chooseAlgoComboBox.addItem(_fromUtf8(""))
        self.chooseAlgoComboBox.addItem(_fromUtf8(""))
        self.chooseAlgorithmsHLayout.addWidget(self.chooseAlgoComboBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.chooseAlgorithmsHLayout.addItem(spacerItem2)
        self.algoConfigButton = QtGui.QPushButton(self.analyseTab)
        self.algoConfigButton.setMinimumSize(QtCore.QSize(150, 0))
        self.algoConfigButton.setObjectName(_fromUtf8("algoConfigButton"))
        self.chooseAlgorithmsHLayout.addWidget(self.algoConfigButton)
        self.verticalLayout_3.addLayout(self.chooseAlgorithmsHLayout)
        self.applyFiltersVLayout_4 = QtGui.QVBoxLayout()
        self.applyFiltersVLayout_4.setObjectName(_fromUtf8("applyFiltersVLayout_4"))
        self.label_29 = QtGui.QLabel(self.analyseTab)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.applyFiltersVLayout_4.addWidget(self.label_29)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.appliedFilterTableWidget = QtGui.QTableWidget(self.analyseTab)
        self.appliedFilterTableWidget.setObjectName(_fromUtf8("appliedFilterTableWidget"))
        self.appliedFilterTableWidget.setColumnCount(0)
        self.appliedFilterTableWidget.setRowCount(0)
        self.horizontalLayout_6.addWidget(self.appliedFilterTableWidget)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.choseFilterComboBox = QtGui.QComboBox(self.analyseTab)
        self.choseFilterComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.choseFilterComboBox.setObjectName(_fromUtf8("choseFilterComboBox"))
        self.choseFilterComboBox.addItem(_fromUtf8(""))
        self.choseFilterComboBox.addItem(_fromUtf8(""))
        self.choseFilterComboBox.addItem(_fromUtf8(""))
        self.choseFilterComboBox.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.choseFilterComboBox)
        self.configureFilterButton = QtGui.QPushButton(self.analyseTab)
        self.configureFilterButton.setMinimumSize(QtCore.QSize(150, 0))
        self.configureFilterButton.setObjectName(_fromUtf8("configureFilterButton"))
        self.verticalLayout_4.addWidget(self.configureFilterButton)
        self.deleteFilterButton = QtGui.QPushButton(self.analyseTab)
        self.deleteFilterButton.setMinimumSize(QtCore.QSize(150, 0))
        self.deleteFilterButton.setObjectName(_fromUtf8("deleteFilterButton"))
        self.verticalLayout_4.addWidget(self.deleteFilterButton)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.addFilterButton = QtGui.QPushButton(self.analyseTab)
        self.addFilterButton.setMinimumSize(QtCore.QSize(150, 0))
        self.addFilterButton.setObjectName(_fromUtf8("addFilterButton"))
        self.verticalLayout_4.addWidget(self.addFilterButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.applyFiltersVLayout_4.addLayout(self.horizontalLayout_6)
        self.line_2 = QtGui.QFrame(self.analyseTab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.applyFiltersVLayout_4.addWidget(self.line_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.applyAlgoButton = QtGui.QPushButton(self.analyseTab)
        self.applyAlgoButton.setMinimumSize(QtCore.QSize(150, 0))
        self.applyAlgoButton.setObjectName(_fromUtf8("applyAlgoButton"))
        self.horizontalLayout_7.addWidget(self.applyAlgoButton)
        self.applyFiltersVLayout_4.addLayout(self.horizontalLayout_7)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.applyFiltersVLayout_4.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.applyFiltersVLayout_4)
        self.ApplyAlgorithmHLayout = QtGui.QHBoxLayout()
        self.ApplyAlgorithmHLayout.setObjectName(_fromUtf8("ApplyAlgorithmHLayout"))
        self.verticalLayout_3.addLayout(self.ApplyAlgorithmHLayout)
        self.line_3 = QtGui.QFrame(self.analyseTab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_3.addWidget(self.line_3)
        self.label_19 = QtGui.QLabel(self.analyseTab)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_3.addWidget(self.label_19)
        self.pipelinesTableWidget = QtGui.QTableWidget(self.analyseTab)
        self.pipelinesTableWidget.setObjectName(_fromUtf8("pipelinesTableWidget"))
        self.pipelinesTableWidget.setColumnCount(0)
        self.pipelinesTableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.pipelinesTableWidget)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.deletePipelineButton = QtGui.QPushButton(self.analyseTab)
        self.deletePipelineButton.setMinimumSize(QtCore.QSize(150, 0))
        self.deletePipelineButton.setObjectName(_fromUtf8("deletePipelineButton"))
        self.horizontalLayout_5.addWidget(self.deletePipelineButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.line = QtGui.QFrame(self.analyseTab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.algorithmResultsVLayout = QtGui.QVBoxLayout()
        self.algorithmResultsVLayout.setObjectName(_fromUtf8("algorithmResultsVLayout"))
        self.label_17 = QtGui.QLabel(self.analyseTab)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.algorithmResultsVLayout.addWidget(self.label_17)
        self.pipelineInfoTextEdit = QtGui.QPlainTextEdit(self.analyseTab)
        self.pipelineInfoTextEdit.setObjectName(_fromUtf8("pipelineInfoTextEdit"))
        self.algorithmResultsVLayout.addWidget(self.pipelineInfoTextEdit)
        self.horizontalLayout.addLayout(self.algorithmResultsVLayout)
        self.tabWidget.addTab(self.analyseTab, _fromUtf8(""))
        self.resultsTab = QtGui.QWidget()
        self.resultsTab.setObjectName(_fromUtf8("resultsTab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.resultsTab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.resultsTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.graphicsView = QtGui.QGraphicsView(self.resultsTab)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.plotLabel1 = QtGui.QLabel(self.resultsTab)
        self.plotLabel1.setMinimumSize(QtCore.QSize(300, 300))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.plotLabel1.setPalette(palette)
        self.plotLabel1.setAutoFillBackground(True)
        self.plotLabel1.setText(_fromUtf8(""))
        self.plotLabel1.setObjectName(_fromUtf8("plotLabel1"))
        self.horizontalLayout_2.addWidget(self.plotLabel1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.resultsTab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1185, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuBearbeiten = QtGui.QMenu(self.menubar)
        self.menuBearbeiten.setObjectName(_fromUtf8("menuBearbeiten"))
        self.menuHilfe = QtGui.QMenu(self.menubar)
        self.menuHilfe.setObjectName(_fromUtf8("menuHilfe"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNewFile = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/New.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionNewFile.setIcon(icon1)
        self.actionNewFile.setObjectName(_fromUtf8("actionNewFile"))
        self.actionOpenNewDatabase = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/OpenNewDatabase.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenNewDatabase.setIcon(icon2)
        self.actionOpenNewDatabase.setObjectName(_fromUtf8("actionOpenNewDatabase"))
        self.actionSaveFile = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveFile.setIcon(icon3)
        self.actionSaveFile.setObjectName(_fromUtf8("actionSaveFile"))
        self.actionQuit = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Quit.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionQuit.setIcon(icon4)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionPrint = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Print.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPrint.setIcon(icon5)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionOnlineAnalysis = QtGui.QAction(MainWindow)
        self.actionOnlineAnalysis.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/OnlineAnalysis.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOnlineAnalysis.setIcon(icon6)
        self.actionOnlineAnalysis.setObjectName(_fromUtf8("actionOnlineAnalysis"))
        self.actionActionOpenProject = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/FileOpen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionActionOpenProject.setIcon(icon7)
        self.actionActionOpenProject.setObjectName(_fromUtf8("actionActionOpenProject"))
        self.actionHilfe = QtGui.QAction(MainWindow)
        self.actionHilfe.setObjectName(_fromUtf8("actionHilfe"))
        self.actionSpeichern_unter = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/SaveAs.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSpeichern_unter.setIcon(icon8)
        self.actionSpeichern_unter.setObjectName(_fromUtf8("actionSpeichern_unter"))
        self.menuFile.addAction(self.actionNewFile)
        self.menuFile.addAction(self.actionActionOpenProject)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSaveFile)
        self.menuFile.addAction(self.actionSpeichern_unter)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuBearbeiten.addAction(self.actionOpenNewDatabase)
        self.menuBearbeiten.addAction(self.actionOnlineAnalysis)
        self.menuHilfe.addAction(self.actionHilfe)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBearbeiten.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())
        self.toolBar.addAction(self.actionNewFile)
        self.toolBar.addAction(self.actionActionOpenProject)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSaveFile)
        self.toolBar.addAction(self.actionSpeichern_unter)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOpenNewDatabase)
        self.toolBar.addAction(self.actionOnlineAnalysis)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addSeparator()
        self.label_16.setBuddy(self.chooseAlgoComboBox)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Prototyp - Automatisierte industrielle Datenanalyse", None))
        self.connectToDatabasePushButton.setText(_translate("MainWindow", "Datenbankverbindung Herstellen", None))
        self.startLoggingSimulationPushButton.setText(_translate("MainWindow", "Start Logging Simulation", None))
        self.label_21.setText(_translate("MainWindow", "Werkstück", None))
        self.currentDatabaseConnectionLabel.setText(_translate("MainWindow", "Datenbank Name + Tabelle Name", None))
        self.addEntryButton.setText(_translate("MainWindow", "&Add Entry", None))
        self.deleteEntryButton.setText(_translate("MainWindow", "&Delete Entry", None))
        self.editButton.setText(_translate("MainWindow", "Edit E&ntry", None))
        self.editCategoriesButton.setText(_translate("MainWindow", "Ed&it Categories", None))
        self.deleteTableButton.setText(_translate("MainWindow", "Delete &Table", None))
        self.quitButton.setText(_translate("MainWindow", "&Close Connection", None))
        self.label_5.setText(_translate("MainWindow", "Datenbank Verbindung", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataintegrationTab), _translate("MainWindow", "Datenintegration", None))
        self.label_18.setText(_translate("MainWindow", "Analyseverfahren", None))
        self.label_16.setText(_translate("MainWindow", "&Algorithmus", None))
        self.chooseAlgoComboBox.setItemText(0, _translate("MainWindow", "KNeighborsClassifier", None))
        self.chooseAlgoComboBox.setItemText(1, _translate("MainWindow", "SimpleKMeans", None))
        self.algoConfigButton.setText(_translate("MainWindow", "Konfiguration", None))
        self.label_29.setText(_translate("MainWindow", " Filter", None))
        self.choseFilterComboBox.setItemText(0, _translate("MainWindow", "None", None))
        self.choseFilterComboBox.setItemText(1, _translate("MainWindow", "MinMaxFilter", None))
        self.choseFilterComboBox.setItemText(2, _translate("MainWindow", "Extremwertfilter", None))
        self.choseFilterComboBox.setItemText(3, _translate("MainWindow", "Median", None))
        self.configureFilterButton.setText(_translate("MainWindow", "Konfiguration", None))
        self.deleteFilterButton.setText(_translate("MainWindow", "Entfernen", None))
        self.addFilterButton.setText(_translate("MainWindow", "Filter Hinzufügen", None))
        self.applyAlgoButton.setText(_translate("MainWindow", "Anwenden", None))
        self.label_19.setText(_translate("MainWindow", "Liste angewandter Pipelines", None))
        self.deletePipelineButton.setText(_translate("MainWindow", "Entfernen", None))
        self.label_17.setText(_translate("MainWindow", "Analyse Ergebnisse", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analyseTab), _translate("MainWindow", "Analyse", None))
        self.label.setText(_translate("MainWindow", "Empfehlungen", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.resultsTab), _translate("MainWindow", "Auswertung", None))
        self.menuFile.setTitle(_translate("MainWindow", "Datei", None))
        self.menuBearbeiten.setTitle(_translate("MainWindow", "Bearbeiten", None))
        self.menuHilfe.setTitle(_translate("MainWindow", "Hilfe", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionNewFile.setText(_translate("MainWindow", "Neu...", None))
        self.actionNewFile.setIconText(_translate("MainWindow", "Neu...", None))
        self.actionNewFile.setToolTip(_translate("MainWindow", "Open New File", None))
        self.actionNewFile.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionOpenNewDatabase.setText(_translate("MainWindow", "Neue Datenbank Verbindung", None))
        self.actionOpenNewDatabase.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionSaveFile.setText(_translate("MainWindow", "Speichern", None))
        self.actionSaveFile.setToolTip(_translate("MainWindow", "Save Current Project", None))
        self.actionSaveFile.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setToolTip(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionPrint.setText(_translate("MainWindow", "Drucken", None))
        self.actionPrint.setToolTip(_translate("MainWindow", "Print Results", None))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.actionOnlineAnalysis.setText(_translate("MainWindow", "Aktiviere Online Analyse", None))
        self.actionOnlineAnalysis.setToolTip(_translate("MainWindow", "Aktiviere/Deaktiviere die Online Analyse von Daten", None))
        self.actionOnlineAnalysis.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionActionOpenProject.setText(_translate("MainWindow", "Öffnen...", None))
        self.actionActionOpenProject.setIconText(_translate("MainWindow", "Öffnen...", None))
        self.actionActionOpenProject.setToolTip(_translate("MainWindow", "Öffne Projekt", None))
        self.actionHilfe.setText(_translate("MainWindow", "Hilfe", None))
        self.actionSpeichern_unter.setText(_translate("MainWindow", "Speichern unter", None))
        self.actionSpeichern_unter.setToolTip(_translate("MainWindow", "Speichern unter", None))

import resources_rc
