# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20170821_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='RMSE',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
