# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20170821_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='RMSE',
        ),
        migrations.AddField(
            model_name='result',
            name='Rmse',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
